// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY864K1Mgtj_QHjecV-dNSmgm3fp_e9-o',
    appId: '1:315539143951:web:21f49fb4b1ab3ec985927a',
    messagingSenderId: '315539143951',
    projectId: 'aerosaur-35c8a',
    authDomain: 'aerosaur-35c8a.firebaseapp.com',
    storageBucket: 'aerosaur-35c8a.firebasestorage.app',
    measurementId: 'G-L2EPE1705K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPunkSZ6LFKAsScZErkqs7y4i8AloqVR4',
    appId: '1:315539143951:android:b37674b20ad8a92485927a',
    messagingSenderId: '315539143951',
    projectId: 'aerosaur-35c8a',
    storageBucket: 'aerosaur-35c8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAONVqNVWUQf0S8TVfszddVoFKWRYKHlX8',
    appId: '1:315539143951:ios:227180f6cf05e02485927a',
    messagingSenderId: '315539143951',
    projectId: 'aerosaur-35c8a',
    storageBucket: 'aerosaur-35c8a.firebasestorage.app',
    iosClientId: '315539143951-q0tsk8vd15uns6d9m0nj1g36bvb9hq9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAONVqNVWUQf0S8TVfszddVoFKWRYKHlX8',
    appId: '1:315539143951:ios:227180f6cf05e02485927a',
    messagingSenderId: '315539143951',
    projectId: 'aerosaur-35c8a',
    storageBucket: 'aerosaur-35c8a.firebasestorage.app',
    iosClientId: '315539143951-q0tsk8vd15uns6d9m0nj1g36bvb9hq9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY864K1Mgtj_QHjecV-dNSmgm3fp_e9-o',
    appId: '1:315539143951:web:e3227a6b6ec8bb2585927a',
    messagingSenderId: '315539143951',
    projectId: 'aerosaur-35c8a',
    authDomain: 'aerosaur-35c8a.firebaseapp.com',
    storageBucket: 'aerosaur-35c8a.firebasestorage.app',
    measurementId: 'G-5JWMVEY6GK',
  );
}
